var x = 4;
var y = -x;
console.log("value of x: ", x);
console.log("value of y: ", y);
var msg = "hello" + "world";
console.log(msg);
var nume = -2;
var result = nume > 0 ? "positive" : "non-positive";
console.log(result);
var numer = 12;
console.log(typeof numer);
